### ISSUE TITLE
Add fnva@gft.com to owner's list

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/adaptive-arp-api-lib-darwin#11]
https://guides.cocoapods.org/making/getting-setup-with-trunk
- Clone this repo
- run the following command:

```
pod trunk add-owner AdaptiveArpApi fnva@gft.com
```

**Comment by carloslozano** [comment]
Anonymous-2:adaptive-arp-api-lib-darwin clozano$ pod trunk add-owner AdaptiveArpApi fnva@gft.com
- Owners:
  - Carlos Lozano carlos@adaptive.me
  - Ferran Vilà Conesa fnva@gft.com
